name: Test make setup

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04,]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run bootstrap
        run: curl https://raw.githubusercontent.com/uesugi6111/isucript/master/bootstrap -O && chmod +x bootstrap && ./bootstrap
